### ISSUE TITLE
[1.18.1] Mod Support

### ISSUE THREAD

**Issue by Matthysse** [bl4ckscor3/SnowUnderTrees#5]
Hello!
Would be nice if snow could generate under modded trees as well (here for example snow doesn't generate under fir trees from Biomes O Plenty 1.18.1);
![2022-01-01_17 42 46](https://user-images.githubusercontent.com/32510957/147873907-9e3683a2-9ec5-46e7-ab55-574168d370a0.png)

**Comment by bl4ckscor3** [comment]
Whether it's a modded tree does not matter. What matters for generating snow under a tree is that all blocks above the ground block are leaves/air/snow - effectively there need not be any branches. As you can see in this image, Snow Under Trees does successfully generate snow under this fir tree wherever there is no branch above. ![](https://i.imgur.com/EsZNfp1.png) Additionally, Snow Under Trees adds itself to every biome where the precipitation is set to snow. As I have found out while trying to find out what is wrong here, this is not the case for the fir wood trees' biome biomesoplenty:snowy_coniferous_forest (even though it does snow ingame in that biome, but as far as I am aware that is tied to temperature as well). I would consider this a bug in Biomes O' Plenty, and not Snow Under Trees.
What I can do to deal with issue like these is add a configuration option which allows people to manually define biomes that snow should generate in.

EDIT: On second thought, I will add an additional check for temperature instead of the additional config option. That should cover biomes that have the correct temperature for it to snow, but are incorrectly marked as not snowing.
