### ISSUE TITLE
Modded Dimension support

### ISSUE THREAD

**Issue by Matthysse** [bl4ckscor3/SnowUnderTrees#6]
Hello, it's me again!
This time, I would like to suggest to support generating snow under trees in other dimensions mod, for example in the Blue Skies dimensions, because it looks like this :
![2022-01-13_15 14 42](https://user-images.githubusercontent.com/32510957/149346984-11decf0f-73af-4cf0-ad4e-f1f50c3dac44.png)

**Comment by bl4ckscor3** [comment]
Looking into this, I was able to verify that Snow Under Trees does indeed add its feature to the snow covered pines biome (the one in the screenshot) of this mod. From that side, it should work in this modded dimension, because as long as the feature is added to a biome, it should work no matter the dimension (vanilla, datapack, modded, ...). However, checking whether the feature is still added to this specific biome when it's being generated yields a no (contrary to other biomes where Snow Under Trees does work). As far as I know, this can really only happen if something resets the generation settings of the biome at some point between Snow Under Trees adding its feature to them and Minecraft generating the world. Thus I conclude this is a bug out of my control.
